name: First interaction
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #workflow_dispatch:

jobs:
  postgres-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: postgres up
        run: docker-compose up -d db | tee build.log
        
  java-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: adopt-openj9
      - name: mvn clean install
        run: mvn clean install         

    
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_API_NAME: "soccer-app"
          HEROKU_EMAIL: kaiquejuvencio@hotmail.com
