name: First interaction
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  
  java-teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        #uses: actions/setup-java@v1
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: adopt-openj9
      - name: db-up
        run: docker-compose up db -d
      - name: clean install
        run: mvn clean install
      #- name: Build Docker image
       # run: docker-compose up --build
      #- name: Build with Maven
      # run: mvn clean install
    
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'kaique.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy dev
