name: First interaction
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #workflow_dispatch:

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: adopt-openj9
      - name: clean install
        run: mvn clean install
        
  container-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker-compose up --build
    
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'kaique.com'
    needs: java-build
    steps:
      - name: Run a one-line script
        run: echo Deploy dev
